name: Component Detection

on:
  workflow_dispatch:

permissions: 
  id-token: write
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Component detection 
        uses: advanced-security/component-detection-dependency-submission-action@v0.0.2
        with:
          detectorsFilter: nuget
